config/routes.rb
Rails.application.routes.draw do

  root 'users#index'
  
  get 'access/login', to: 'access#login', as: 'login'
  post 'access/attempt_login', to: 'access#attempt_login', as: 'attempt_login'
  get 'access/logout', to: 'access#logout', as: 'logout'

  resources :plus_one, only: :create
  #get 'plus_one'
  resources :skills, only: [:show, :create, :new]

  resources :users, only: [:index, :show]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/skill.rb
class Skill < ApplicationRecord
	has_many :user_skills
	has_many :users, through: :user_skills

	validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
	has_many :user_skills
	has_many :skills, through: :user_skills

	has_secure_password
	validates :name, presence: true
end

app/models/user_skill.rb
class UserSkill < ApplicationRecord
  belongs_to :user
  belongs_to :skill

  default_scope {order(plus_count: :desc)}
end

app/controllers/access_controller.rb
class AccessController < ApplicationController
  def login
  end

  def attempt_login
  	if params[:name].present? && params[:password].present?
  		found_user = User.where(name: params[:name]).first
  		if found_user
  			authorized_user = found_user.authenticate(params[:password])

  		end
  	end

  	if authorized_user
  		session[:user_id] = authorized_user.id
  		flash[:notice] = "logged in successfully!"
  		redirect_to(user_path(authorized_user))
  	else
  		flash[:notice] = "invalid name/password"
  		render 'login'
  	end
  end

  def logout
  	session[:user_id] = nil
  	flash[:notice] = "logged out!"
  	redirect_to(login_path)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
helper_method :current_user
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  


  private

  def confirm_logged_in
  	unless session[:user_id]
  		flash[:notice] = "Please log in"
  		redirect_to(login_path)
  	end
  end

end

app/controllers/plus_one_controller.rb
class PlusOneController < ApplicationController
	before_action :confirm_logged_in
	def create
		@user_skill = UserSkill.where(user: params[:user]).where(skill: params[:skill]).first
  		unless @user_skill.users_clicked.include? Integer(params[:current_user])
  			@user_skill.plus_count += 1
	  		@user_skill.users_clicked << params[:current_user]
	  		@user_skill.save
  		end
  		redirect_to(user_path(params[:user]))
	end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController

  before_action :confirm_logged_in

  def new
  	@user = User.find(params[:user_id])
  	@skill = @user.skills.new
  end

  def create
  	@user = User.find(params[:user_id])
    @skill = Skill.where('lower(name) = ?', skill_params[:name].downcase).first 
    @skill ||= Skill.new(skill_params)
  	if @skill.save
      @skill.users << @user
      flash[:notice] = "Skill added successfully."
      redirect_to(user_path(@user))
    else
      render('new')
    end
  end

  def show
  	@skill = Skill.includes(:users).find(params[:id])
  end

  private
  def skill_params
  	params.require(:skill).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :confirm_logged_in
  
  def index
    @users = User.all
  end

  def show
  	@user = User.includes(:skills).find(params[:id])
  end

  def plus_count(user, skill)
  	@user_skill = UserSkill.where(user: user).where(skill: skill).first
  	@user_skill.plus_count
  end

  helper_method :plus_count
end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

	def error_message_for(object)
		render(:partial => 'layouts/error_messages', 
			:locals => {:object => object})
	end
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/access/login.html.erb
<div class="container">
    <div class="row vertical-offset-50">
      <div class="col-md-4 col-md-offset-4">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Welcome, Login Now!</h3>
          </div>
          <div class="panel-body">
            <%= form_tag(attempt_login_path, :method => :post) do %>
            <table>
              <tr>
                <td><%= label_tag(:name) %></td>
                <td><%= text_field_tag(:name) %></td>
              </tr>
              <tr>
                <td><%= label_tag(:password) %></td>
                <td><%= password_field_tag(:password) %></td>
              </tr>
              <tr>
                <td>&nbsp;</td>
                <td><%= submit_tag("Log In") %></td>
              </tr>
            </table>
            <% end %>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_error_messages.html.erb
<% if  object && object.errors.size >  0 %>
	<div class="alert alert-danger">
		<h4><%= pluralize(object.errors.size, "error") %> prohibited this record from being saved</h4>
		<p>There was problems with the following fields: </p>
		<ul>
			<% object.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wantedly</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
            <a class="navbar-brand">Wantedly</a>
        </div>
        <div class="nav navbar-nav navbar-right">
          <% if current_user %>
              <li><strong><span class="glyphicon glyphicon-user"></span> Logged in as <%= current_user.name %>&nbsp;&nbsp;&nbsp;&nbsp;</strong> </li>
              <li><strong> <%= link_to "Profile", user_path(current_user)%>&nbsp;&nbsp;&nbsp;&nbsp;</strong> </li>
              <li><strong> <%= link_to "Users", users_path%>&nbsp;&nbsp;&nbsp;&nbsp;</strong> </li>
              <li><span class="glyphicon glyphicon-log-out"><%= link_to "Logout", logout_path%>&nbsp;</span></li>
          <% else %>
           <li> <%= link_to 'Login', login_path %> </li>
        <% end %>
        </div>
    </div>
  </nav>

  <div class="container">
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <%= flash[:notice] %>
      </div>
    <% end %>
    
  </div>
    

    <%= yield %>

  </div>
  </body>
</html>

app/views/skills/new.html.erb
<%= form_for(@skill, url: skills_path(user_id: @user.id)) do |f| %>
	<%= error_message_for(f.object) %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<%= f.submit("Add Skill") %>
<% end %>

app/views/skills/show.html.erb
<div class="container">
  <div class="jumbotron">
    <h1><%=@skill.name%></h1> 
  </div>

  <ul>
	<% @skill.users.each do |user| %>
		<h1><span class="label"><%=link_to(user.name, user_path(user))%></span></h1>

	<% end %>
  </ul>
</div>

app/views/users/index.html.erb
<div class="jumbotron text-center">
  <h1>Mini-Wantedly Clone!</h1>
  <p>reproduce skill section of Wantedly profile</p> 
</div>

<h1>Users</h1>
<% @users.each do |user| %>
	<ul>
		<li><%=link_to(user.name, user_path(user))%></li>
	</ul>
<% end %>

app/views/users/show.html.erb
<div class="row">
	<div class="col-md-2">
		<h3><%=@user.name%></h3>
	</div>
</div>

<div class="row">
	<div class="col-md-12">
		<h3>Skills: </h3>
	<ul>
	<% @user.skills.each do |skill| %>
		<li>
			<div class="col-md-2"><span class="badge"> <%= plus_count(@user, skill) %> </span>
				<%= link_to(skill.name, skill_path(skill.id))%> </div>
			<% unless current_user == @user %>
			<div class="col-md-1"><%= link_to '<i class="glyphicon glyphicons-plus"></i> +1'.html_safe, plus_one_index_path(user: @user, skill: skill, current_user: current_user), method: :post, class: 'label label-primary' %> </div>

			<% end %>
		</li>
		<% end %>
	</ul>
	<% if current_user == @user %>
	<%= link_to '<i class="glyphicon glyphicons-plus"></i> Add New Skill'.html_safe, new_skill_path(user_id: @user.id), class: 'btn btn-primary btn-md' %>
	<% end %>
	</div>
</div>